/* Lingora Supabase authentication bootstrap. */
const LINGORA_SUPABASE_URL='https://usgskxpkkjeirrdbesku.supabase.co';
const LINGORA_SUPABASE_PUBLISHABLE_KEY='sb_publishable_0Tl1dLl9gS_hJODfXU4A3A_acN6efcq';
(function(){
 const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=boot;document.head.appendChild(s);
 function boot(){const client=supabase.createClient(LINGORA_SUPABASE_URL,LINGORA_SUPABASE_PUBLISHABLE_KEY);window.lingoraSupabase=client;const buttons=document.querySelectorAll('.actions .btn');if(buttons.length>=2){buttons[0].onclick=()=>openAuth('login');buttons[1].onclick=()=>openAuth('signup')}client.auth.getSession().then(({data})=>updateHeader(data.session));client.auth.onAuthStateChange((_e,session)=>updateHeader(session));window.lingoraAuth={client,openAuth}}
 function updateHeader(session){const box=document.querySelector('.actions');if(!box)return;if(session){const email=session.user.email||'Account';box.innerHTML=`<span style="align-self:center;font-size:13px;color:#687386">${escapeHtml(email)}</span><button class="btn light" id="logoutBtn">Log out</button>`;document.getElementById('logoutBtn').onclick=()=>window.lingoraSupabase.auth.signOut()}}
 function openAuth(mode){let m=document.getElementById('authModal');if(!m){m=document.createElement('div');m.id='authModal';m.className='modal';m.innerHTML=`<div class="box"><button class="close" id="authClose">×</button><h2 id="authTitle"></h2><p class="muted" id="authIntro"></p><div><input id="authName" class="field2" placeholder="Your name"><input id="authEmail" class="field2" type="email" placeholder="Email"><input id="authPassword" class="field2" type="password" placeholder="Password (6+ characters)"><select id="authRole" class="field2"><option value="student">I want to learn</option><option value="tutor">I want to teach</option></select><button class="btn primary" id="authSubmit" style="width:100%;margin-top:8px"></button><button class="btn light" id="authSwitch" style="width:100%;margin-top:8px"></button><p id="authMsg" class="muted" style="font-size:13px"></p></div></div>`;document.body.appendChild(m);document.getElementById('authClose').onclick=()=>m.classList.remove('show')}
 const signup=mode==='signup';document.getElementById('authTitle').textContent=signup?'Create your Lingora account':'Welcome back';document.getElementById('authIntro').textContent=signup?'Join as a student or tutor.':'Log in to your Lingora account.';document.getElementById('authName').style.display=signup?'block':'none';document.getElementById('authRole').style.display=signup?'block':'none';document.getElementById('authSubmit').textContent=signup?'Create account':'Log in';document.getElementById('authSwitch').textContent=signup?'I already have an account':'Create a new account';document.getElementById('authMsg').textContent='';document.getElementById('authSwitch').onclick=()=>openAuth(signup?'login':'signup');
 document.getElementById('authSubmit').onclick=async()=>{const email=document.getElementById('authEmail').value.trim(),password=document.getElementById('authPassword').value,msg=document.getElementById('authMsg');if(!email||!password){msg.textContent='Please enter your email and password.';return}msg.textContent='Working…';const c=window.lingoraSupabase;if(signup){const name=document.getElementById('authName').value.trim(),role=document.getElementById('authRole').value;const {data,error}=await c.auth.signUp({email,password,options:{data:{full_name:name||email.split('@')[0],role}}});if(error){msg.textContent=error.message;return}msg.textContent=data.session?'Account created successfully.':'Account created. Check your email to confirm your account.'}else{const {error}=await c.auth.signInWithPassword({email,password});msg.textContent=error?error.message:'Logged in successfully.';if(!error)setTimeout(()=>m.classList.remove('show'),700)}};m.classList.add('show')}
 function escapeHtml(v){return v.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();